### ISSUE TITLE
Bug on Remove Translation

### ISSUE THREAD

**Issue by tiendat77** [kyoz/loz#9]
**Describe the bug**
When I removed a translation key by right-click on the tree, all the translation content disappear.

I have selected "Auto save" option, and now it's really hard to undo it

**To Reproduce**
1. Open new project
2. Right click on the tree of  translation keys
3. Select "Remove Translation"
4. Translation key that I selected has been removed and ALL ANOTHER TRANSLATION CONTENTS REMOVED TOO???

**Screenshots**
![Screenshot from 2021-06-26 13-34-15](https://user-images.githubusercontent.com/37741900/123504401-40229480-d683-11eb-8f72-9111c68eea34.png)

My i18n file after remove translation key:
![Screenshot from 2021-06-26 13-32-16](https://user-images.githubusercontent.com/37741900/123504407-516ba100-d683-11eb-8771-0fd6d984e75e.png)

I will appreciate if you fix it as soon as possible
Many thanks!

**Comment by kyoz** [comment]
@tiendat77 Fixed. Please try it again bro :))

**Comment by kyoz** [comment]
No, Test carefully bro :))

**Comment by tiendat77** [comment]
It's work fine. Thanks ❤️
